### ISSUE TITLE
What about GraphQL?

### ISSUE THREAD

**Issue by gokaygurcan** [shieldfy/API-Security-Checklist#10]
Hello,

It seems that this repository was made only for RESTful APIs. Maybe it would be nice to add a section for [GraphQL](http://graphql.org), which is a nice alternative to REST. 

What do you think?

**Comment by racerxdl** [comment]
Agreed. Most of the rules apply for GraphQL as well but some of them aren't applicable (since its not security issue but RESTful best pratices) like:

- Use proper HTTP method according to operation , GET (read), POST (create), PUT (replace/update) and DELETE (to delete a record).
- Return the proper status code according to the operation completed. (e.g. 200 OK , 400 Bad Request , 401 Unauthorized, 405 Method Not Allowed ... etc).

**Comment by netcode** [comment]
Interesting to mention GraphQL here, but I agree that it will be hard to merge the GraphQL into the list. Many points will not be applicable.
