### ISSUE TITLE
OAuth referred to as AuthN

### ISSUE THREAD

**Issue by garthoid** [shieldfy/API-Security-Checklist#169]
This may sound pedantic but I hear it all the time and it leads to confusion about OAuth.
OAuth is not an authentication (AuthN) mechanism, it is an authorization mechanism (AuthZ) which relies on an authorization service or identity provider to confirm the identity of the principal. OIDC might be one mechanism to support this.

Please remove OAuth from the line in authentication section:
"Don't use Basic Auth. Use standard authentication instead (e.g., [JWT](https://jwt.io/), [OAuth](https://oauth.net/))."

**Comment by Maikuolan** [comment]
We probably should, in addition, have some kind of definition, or at least clarification, for what exactly we mean by "standard authentication" (or then, there's question of whether it would be better to have "standard authentication" or "standard authorization" as the recommendation written there in the first place). Given that this is a "checklist" rather than in-depth learning resource or the likes of, presumably done just as a simple link embedded within the recommendation pointing to such a resource, rather than writing such definitions or clarifications into the checklist itself directly. For the benefit of the security-illiterate, for those that don't already know the difference et al, it may provide a stronger point of reference for them to understand *why* such a change would be implemented in the first place (because I could envision a counter-argument such as *"Why even worry about that? The implications and end-results are the same anyway!"* arising). *(Related to #8)*.

**Comment by mattspiekerman** [comment]
I'm new to GitHub and the open source community, I saw this proposed change and understand what is being requested. Is it ok for me to make the change as a way to get familiar with contributing to open source projects?

**Comment by Maikuolan** [comment]
Go for it. :-)

Public contributions are welcome at this repository.

**Comment by Maikuolan** [comment]
Merged. :+1:
