### ISSUE TITLE
Translation for korean

### ISSUE THREAD

**Issue by mingrammer** [shieldfy/API-Security-Checklist#33]
I want to translate this repo to korean. How do I do this? Would I send a PR for korean README to you?

Thanks :)

**Comment by Maikuolan** [comment]
I don't think any formal procedures or contribution guidelines exist yet (extremely successfully trending repository at **4,251 stars [!!]** currently, but only 3 days old currently nonetheless), but what I would recommend for now (until @netcode writes some formal procedures or contribution guidelines), based on precedence (what other contributors have already done), is *fork* the repository, translate the *README.md* file, write the translations to a file named like *README-ko.md* (*ko* because of the language code for Korean), and send a *pull request* for it.

There's a completed Chinese translation which has been accepted, named as *README-zh.md*, and there's a completed Brazilian Portuguese translation in one of the current pull requests, named as *README-pt_BR.md*, so, I think that naming schema (*README-[L10N-code].md*) should be okay to use.

Currently, also, with the other two translations, a link to the completed translation file has been added into each of the other two current versions of the README (although at the moment, it may be better to send separate pull requests for changes to each modified file, due to the number and frequency of pull requests currently being sent to the repository, to avoid the risk of merge conflicts).

**Comment by mingrammer** [comment]
@Maikuolan Thanks for reply. I'll send a PR for korean soon.

**Comment by netcode** [comment]
Thanks @mingrammer  @Maikuolan  
merged #36
